services:
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: mydata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dbnet  

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres
  webflask:
    build: ./flaskprj
    image:
      flask-back
    container_name: flsite
    links:
      - "postgres:dbps"
    networks:
      - dbnet
    volumes:
      - ./flaskprj:/app
    ports:
      - "127.0.0.1:8000:4000"  
    depends_on:
      - postgres

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data:

  # docker run -d --rm --name psgr --network dbnet -e POSTGRES_DB=mydata 
  # -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=1234 
  # -v postgres-data:/var/lib/postgresql/data postgres:17-alpine
  # docker compose up




  #  docker run --rm --network dbnet --link psgr:dbps -p 8000:4000 -v ${PWD}/flaskprj -d flask-back